version: '3.9'
services:
  nextjs:
    image: node:18-alpine
    container_name: workflo_nextjs
    working_dir: /app
    volumes:
      - /var/lib/docker/volumes/next-js_nextjs_app/_data/app:/app
      # Remove the git_config volume - it's causing the issue
    command: |
      sh -c "
      # Install git
      apk add --no-cache git &&
      
      # Configure git
      git config --global user.email 'florian@workflo.nl' &&
      git config --global user.name 'WORKFL0' &&
      git config --global credential.helper store &&
      
      # Clone interactively first time
      if [ ! -d /app/.git ]; then
        echo '==================================' &&
        echo 'First time setup - need to clone repository' &&
        echo 'Please run: docker exec -it workflo_nextjs sh' &&
        echo 'Then run: git clone https://github.com/WORKFL0/site.git .' &&
        echo '==================================' &&
        sleep 3600
      else
        # If already cloned, just pull and run
        cd / && rm -rf /app && git clone git@github.com:WORKFL0/site.git /app &&         cd /app &&         yarn install &&         yarn dev
      fi
      "
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_SANITY_PROJECT_ID=${NEXT_PUBLIC_SANITY_PROJECT_ID}
      - NEXT_PUBLIC_SANITY_DATASET=${NEXT_PUBLIC_SANITY_DATASET}
      - SANITY_API_TOKEN=${SANITY_API_TOKEN}
      - NEXT_PUBLIC_SITE_URL=https://nextjs.workflo.it
    restart: unless-stopped
    ports:
      - "3000:3000"

  sanity:
    image: node:18-alpine
    container_name: workflo_sanity
    working_dir: /app
    volumes:
      - sanity_app:/app
    command: |
      sh -c "
      yarn install &&
      yarn dev
      "
    environment:
      - NODE_ENV=development
      - SANITY_STUDIO_PROJECT_ID=${NEXT_PUBLIC_SANITY_PROJECT_ID}
      - SANITY_STUDIO_DATASET=${NEXT_PUBLIC_SANITY_DATASET}
    restart: unless-stopped
    ports:
      - "3333:3333"

volumes:
  nextjs_app:
  sanity_app: