- id: 364ecc13ef3f444e99787190031731b3
  alias: Start HomeKit
  trigger:
  - platform: homeassistant
    event: start
  action:
  - delay: 00:05
  - service: homekit.reload
    data: {}
  initial_state: true
- id: '004'
  alias: tesla_climatisation_on
  trigger:
  - entity_id: climate.flomobiel_hvac_climate_system
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data_template:
      message: Tesla climatisation started
      title: Tesla climatisation started
    service: notify.mobile_app_flophone12
  mode: single
- id: '006'
  alias: tesla_carid_charging
  trigger:
  - entity_id: switch.flomobiel_charger_switch
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data_template:
      message: Tesla is now charging
      title: Tesla is now charging
    service: notify.mobile_app_flophone12
  mode: single
- id: '007'
  alias: tesla_carid_battery_fully_charged
  trigger:
  - above: 80
    entity_id: sensor.flomobiel_battery_sensor
    platform: numeric_state
  action:
  - data_template:
      message: Tesla is now fully charged
      title: Tesla is now fully charged
    service: notify.mobile_app_flophone12
  mode: single
- id: '1560464670808'
  alias: reset pir01
  description: Gang
  trigger:
  - entity_id: binary_sensor.433_motion_01
    for: 0:00:10
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.433_motion_01
    state: 'on'
  action:
  - data:
      payload: ED0A0Eoff
      topic: tele/sonoff-00/RESULT
    service: mqtt.publish
- id: '1560464670809'
  alias: reset pir02
  description: Keuken
  trigger:
  - entity_id: binary_sensor.433_motion_02
    for: 0:00:10
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.433_motion_02
    state: 'on'
  action:
  - data:
      payload: ED408Eoff
      topic: tele/sonoff-00/RESULT
    service: mqtt.publish
- id: '1575503941622'
  alias: reset pir03
  description: Badkamer
  trigger:
  - entity_id: binary_sensor.433_motion_03
    for: 0:00:10
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.433_motion_03
    state: 'on'
  action:
  - data:
      payload: EDA16Eoff
      topic: tele/sonoff-00/RESULT
    service: mqtt.publish
- id: '1578155741364'
  alias: Notify.C.left_work
  description: ''
  trigger:
  - entity_id: person.cindy
    event: leave
    platform: zone
    zone: zone.work_kopzorgen_2
  condition: []
  action:
  - data:
      message: "Wuhoe Cindy heeft zojuist haar werk verlaten \U0001F389"
      title: Werkdag is voorbij
    action: notify.mobile_app_flophone15pro
  mode: single
- id: '1578605542949'
  alias: turn off heating bed
  description: ''
  triggers:
  - entity_id:
    - switch.tp_01
    for:
      hours: 0
      minutes: 45
      seconds: 0
    to: 'on'
    trigger: state
  conditions: []
  actions:
  - action: switch.turn_off
    data: {}
    target:
      entity_id: switch.tp_01
- id: '1586021452439'
  alias: BathroomFanOnShoowering
  description: ''
  trigger:
  - above: 93
    entity_id: sensor.badkamer_humidity
    platform: numeric_state
  condition: []
  action:
  - data: {}
    entity_id: switch.shelly_01
    service: switch.turn_on
- id: '1586021524757'
  alias: BathroomFanOffShoowering
  description: ''
  trigger:
  - below: 93
    entity_id: sensor.badkamer_humidity
    platform: numeric_state
  condition: []
  action:
  - data: {}
    entity_id: switch.shelly_01
    service: switch.turn_off
- id: '1602254699776'
  alias: Turn Bath Automation OFF
  description: ''
  trigger:
  - platform: time
    at: '11:00'
  condition: []
  action:
  - service: automation.turn_off
    data: {}
    entity_id: automation.bathroomfanonshoowering
  mode: single
- id: '1602254772624'
  alias: Turn Bath Automation ON
  description: ''
  trigger:
  - platform: time
    at: 06:00
  condition: []
  action:
  - service: automation.turn_on
    data: {}
    entity_id: automation.bathroomfanonshoowering
  mode: single
- id: '1616416760208'
  alias: ShowerStateOn
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.advanced_programmable_thermostat_for_heating_systems_humidity
    above: '80'
    for: 00:01:00
  condition: []
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.showeron
  mode: single
- id: '1616416788374'
  alias: ShowerStateOff
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.advanced_programmable_thermostat_for_heating_systems_humidity
    for: 00:01:00
    below: '80'
  condition: []
  action:
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.showeron
  mode: single
- id: '1624181197768'
  alias: Tag 001 is gescand
  description: ''
  trigger:
  - platform: tag
    tag_id: ee36a663-b1da-4f12-98c1-754ddc370ed5
  condition: []
  action:
  - service: light.toggle
    target:
      area_id: f9f6cbf3175543cba93284a3ba464ead
      device_id: 9653cf84c2c84ae1b4db7181b30677a9
    data:
      transition: 22
  mode: single
- id: '1632234753291'
  alias: Doorbird Ring
  description: Voordeur bel ingedrukt
  trigger:
  - platform: event
    event_type: doorstation_1ccae3737e3d_somebody_pressed_the_button
  condition: []
  action:
  - service: tts.google_translate_say
    data:
      entity_id: media_player.badkamer
      message: Hallo, er staat iemand aan de deur
  - service: tts.google_translate_say
    data:
      entity_id: media_player.beneden
      message: DING, DONG! Hallo, er staat iemand aan de deur
  - service: tts.google_translate_say
    data:
      entity_id: media_player.amp
      message: DING, DONG! Hallo, er staat iemand aan de deur
  - service: cast.show_lovelace_view
    data:
      entity_id: media_player.woonkamer
      dashboard_path: https://dwfe7c9499s66fxffaidukom0p7aclla.ui.nabu.casa/api/camera_proxy/camera.blueiris_doorbird_voordeur?token=45cf092da53ce8f81692a7bee4ac2d338e093d16089ed0ffdd890966351f59e1
  - service: media_player.play_media
    target:
      entity_id: media_player.beneden
    data:
      media_content_id: media-source://tts/google_translate?message=DING%2C+DONG%21
      media_content_type: provider
    metadata:
      title: DING, DONG!
      thumbnail: https://brands.home-assistant.io/_/google_translate/logo.png
      media_class: app
      children_media_class:
      navigateIds:
      - {}
      - media_content_type: app
        media_content_id: media-source://tts
      - media_content_type: provider
        media_content_id: media-source://tts/google_translate?message=DING%2C+DONG%21
  - service: tts.google_translate_say
    data:
      entity_id: media_player.beneden
      message: DONG, DONG!
      cache: true
  mode: single
- id: '1666977310972'
  alias: Notify Cin is home
  description: ''
  trigger:
  - platform: zone
    entity_id: person.cindy
    zone: zone.home
    event: enter
  condition: []
  action:
  - service: notify.mobile_app_flophone15pro
    data:
      message: Yeah! Cindy is thuis
      title: Guess who's home
  mode: single
- id: '1666986588058'
  alias: Notify door opend
  description: ''
  triggers:
  - entity_id:
    - binary_sensor.slaapkamerdeur
    from: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 2
    trigger: state
  conditions:
  - condition: sun
    before: sunset
    after: sunrise
    enabled: false
  - condition: time
    after: '23:00:00'
    before: 03:00:00
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
  - condition: state
    entity_id: input_boolean.sleepmode
    state: 'off'
  actions:
  - data:
      message: Someone is awake
      title: Door opend
    action: notify.mobile_app_flophone15pro
  mode: single
- id: '1721855678299'
  alias: Control Roomba based on home presence
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.someone_home
    to: 'off'
    for:
      hours: 0
      minutes: 10
      seconds: 0
  - platform: state
    entity_id:
    - binary_sensor.someone_home
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.roomba_triggered_today
    state: 'off'
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: automation.control_roomba_based_on_home_presence
        state: 'on'
      sequence:
      - service: vacuum.start
        metadata: {}
        data: {}
        target:
          entity_id: vacuum.roomba
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.roomba_triggered_today
        data: {}
    - conditions:
      - condition: state
        entity_id: automation.control_roomba_based_on_home_presence
        state: 'off'
      sequence:
      - service: vacuum.stop
        target:
          entity_id: vacuum.roomba
        data: {}
  mode: single
- id: '1721856632297'
  alias: Resets the Roomba trigger boolean at midnight
  description: ''
  trigger:
  - platform: time
    at: 00:00:00
  condition: []
  action:
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.roomba_triggered_today
    data: {}
  mode: single
- id: '1724316891349'
  alias: Uptime Kuma Notification
  description: Stuur een notificatie naar mobile_app_flophone15pro op basis van Uptime
    Kuma event
  triggers:
  - event_type: call_service
    event_data:
      domain: notify
      service: mobile_app_flophone15pro
    trigger: event
    context:
      user_id:
      - adcd17a955c24612ad14765d539e92a6
  conditions:
  - condition: sun
    before: sunset
    after: sunrise
  actions:
  - data_template:
      title: "{% if trigger.event.data.service_data.data.status == 0 %}\n  \U0001F6A8
        Uptime Kuma - Service Down\n{% elif trigger.event.data.service_data.data.status
        == 1 %}\n  ✅ Uptime Kuma - Service Up\n{% endif %}\n"
      message: "{% if trigger.event.data.service_data.data.status == 0 %}\n  De service
        '{{ trigger.event.data.service_data.name | default(\"onbekend\") }}' is momenteel
        niet bereikbaar.\n{% elif trigger.event.data.service_data.data.status == 1
        %}\n  De service '{{ trigger.event.data.service_data.name | default(\"onbekend\")
        }}' is weer operationeel.\n{% endif %}\n"
    action: notify.mobile_app_flophone15pro
  mode: single
- id: '1736008634792'
  alias: Vakantie lichten aan18uur
  description: ''
  triggers:
  - trigger: time
    at: '18:00:00'
  conditions: []
  actions:
  - action: light.turn_on
    metadata: {}
    data: {}
    target:
      entity_id:
      - light.slaapkamerhuel
      - light.diner_muur
      - light.hue_artimide_kast
      - light.plant_lamp
  mode: single
- id: '1736009470124'
  alias: Vakantie licht uit23uur
  description: ''
  triggers:
  - trigger: time
    at: '23:00:00'
  conditions: []
  actions:
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      area_id: f9f6cbf3175543cba93284a3ba464ead
  mode: single
- id: '1741266174278'
  alias: Turn off charging after iPhone is charged
  description: ''
  use_blueprint:
    path: vorion/turn-off-phone-charging-after-the-phone-is-charged.yaml
    input:
      switch: switch.stekkerblok_smart_plug_1
      phone_battery: sensor.flophone15pro_battery_level_2
      charged_percent: 90
- id: '1741266258044'
  alias: Turn off charging after iPad is charged
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - sensor.flopadpro_battery_level
    from: 'off'
    to: 'on'
    for:
      hours: 1
      minutes: 0
      seconds: 0
  conditions: []
  actions:
  - entity_id: switch.stekkerblok_smart_plug_2
    action: switch.turn_off
  variables:
    phone_battery: sensor.flopadpro_battery_level
    charged_percent: 90
- id: '1741279905242'
  alias: Tag sleep mode scanned
  description: ''
  triggers:
  - trigger: tag
    tag_id: 02f262ee-0c32-4cd9-aec0-4fbbc5a51772
  conditions: []
  actions:
  - action: input_boolean.toggle
    metadata: {}
    data: {}
    target:
      entity_id: input_boolean.sleepmode
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: scene.naar_bed
  - action: notify.mobile_app_flophone15pro
    metadata: {}
    data:
      message: ZZZZZ. Slaap lekker! Alles staat uit.
  mode: single
- id: '1741280140211'
  alias: Turn off sleep mode
  description: ''
  triggers:
  - trigger: time
    at: 06:00:00
  conditions: []
  actions:
  - action: input_boolean.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: input_boolean.sleepmode
  mode: single
- id: '1741280430714'
  alias: iphone charging toggle sleepmode
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - sensor.flophone15pro_battery_state
    to: Charging
  conditions:
  - condition: time
    after: '22:00:00'
    before: 05:55:00
  actions:
  - action: input_boolean.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: input_boolean.sleepmode
  mode: single
- id: '1741281201012'
  alias: Licht aan bij openen kast Flo
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.kleding_kast_flo
    to: 'on'
  conditions: []
  actions:
  - action: light.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: light.masterslaapkamer
  mode: single
- id: '1741281256028'
  alias: Licht uit na sluiten kast Flo
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.kleding_kast_flo
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 10
  conditions: []
  actions:
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: light.masterslaapkamer
  mode: single
- id: '1741283427345'
  alias: Turn on charging befor iPad is empty
  description: ''
  triggers:
  - entity_id: sensor.flopadpro_battery_level
    trigger: state
  conditions:
  - condition: template
    value_template: '{{ (states(phone_battery)|int) >= (charged_percent|int) }}'
  - condition: time
    before: 06:00:00
    after: '17:00:00'
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
  actions:
  - entity_id: switch.stekkerblok_smart_plug_2
    action: switch.turn_on
  variables:
    phone_battery: sensor.flopadpro_battery_level
    charged_percent: 10
- id: '1741283700506'
  alias: Notify motion
  description: ''
  triggers:
  - entity_id:
    - binary_sensor.slaapkamer_sensor_motion
    trigger: state
    to: 'on'
  conditions:
  - condition: time
    after: '22:00:00'
    before: 06:00:00
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
  - condition: state
    entity_id: input_boolean.sleepmode
    state: 'off'
  - condition: state
    entity_id: binary_sensor.slaapkamerdeur
    state: 'off'
    attribute: device_class
  actions:
  - data:
      message: Someone is awake
      title: Motion
    action: notify.mobile_app_flophone15pro
  mode: single
- id: '1741536886288'
  alias: Turn on stekker1 if iPhone below 20
  description: ''
  triggers:
  - entity_id:
    - sensor.flophone15pro_battery_level
    trigger: state
  conditions:
  - condition: template
    value_template: '{{ (states(phone_battery)|int) >= (charged_percent|int) }}'
  - condition: time
    before: 06:00:00
    after: '17:00:00'
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
  actions:
  - action: switch.turn_on
    data: {}
    target:
      entity_id: switch.stekkerblok_smart_plug_1
  mode: single
  variables:
    phone_battery: sensor.flopadpro_battery_level
    charged_percent: 10
- id: '1746176640168'
  alias: Turn on automation boolians daily sunrise
  description: ''
  triggers:
  - trigger: sun
    event: sunrise
    offset: 01:00:00
  conditions: []
  actions:
  - action: input_boolean.turn_on
    metadata: {}
    data: {}
    target:
      entity_id:
      - input_boolean.woonkamerautomationsonoff
      - input_boolean.keukenautomationsonoff
      - input_boolean.eetkamerautomationsonoff
      - input_boolean.keukendeurautomationsonoff
      - input_boolean.gangautomationsonoff
      - input_boolean.tuinautomationsonoff
  mode: single
