- platform: toon_climate
  name: Toon Thermostat
  host: !secret IP_Toon
  port: 80
  scan_interval: 10
  min_temp: 10.0
  max_temp: 30.0
# Zolder
- platform: generic_thermostat
  name: Office
  heater: switch.smart_switch_6
  target_sensor: sensor.kantoor_air_temperature
  max_temp: 27
  target_temp: 15
