homeassistant:
  customize: !include customize.yaml
default_config:
http:
  use_x_forwarded_for: true
  # trusted_proxies:
  #   # - 127.0.0.1
  #   - 172.16.0.0/12
  #   - 192.168.178.0/24
  #   - 192.168.3.0/24
  #   - 10.66.60.0/24
  trusted_proxies:
      - 127.0.0.1
      - ::1
      - 192.168.178.0/24
  # Cloudflare IPv4 ranges
      - 173.245.48.0/20
      - 103.21.244.0/22
      - 103.22.200.0/22
      - 103.31.4.0/22
      - 141.101.64.0/18
      - 108.162.192.0/18
      - 190.93.240.0/20
      - 188.114.96.0/20
      - 197.234.240.0/22
      - 198.41.128.0/17
      - 162.158.0.0/15
      - 104.16.0.0/13
      - 104.24.0.0/14
      - 172.64.0.0/13
      - 131.0.72.0/22
    # - ::1
  # ssl_certificate: /ssl/origin.pem
  # ssl_key: /ssl/privkey.pem
frontend:
  themes: !include_dir_merge_named themes/
#panel_iframe:
# tasmoadmin:
#   title: "TasmoAdmin"
#   icon: mdi:lightbulb-on
#   url: "http://192.168.178.2:9541"
tts:
  - platform: google_translate
    language: nl
logger:
  default: info
  logs:
    custom_components.toon_climate: debug
    custom_components.tesla_custom: debug
    homeassistant.components.http.ban: info
    homeassistant.components.auth: info
    homeassistant.components.http: warning
logbook:
history:
recorder:
  db_url: !secret mysql_db_link
# tesla:
#   username: !secret email_workflo
#   password: !secret pass_tesla
# tesla_cc: !include tesla.yaml
influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret zijlstraat_nr
  max_retries: 3
  default_measurement: state
# map:
sun:
ssdp:
cloud:
my:
ffmpeg:
stream:
lovelace:
system_health:
# breaking_changes:
light: !include light.yaml
weather: !include weather.yaml
camera: !include cameras.yaml
switch: !include switch.yaml
sensor: !include sensor.yaml
notify: !include notify.yaml
climate: !include climate.yaml
media_player: !include media_player.yaml
binary_sensor: !include binary_sensors.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
input_select: !include input_select.yaml
remote: !include remote.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
# zone: !include zones.yaml
# home_connect:
#   client_id: !secret HomeConnect_CLIENT_ID
#   client_secret: !secret HomeConnect_SECRET
# spotify:
#  client_id: !secret spotify_ID
#  client_secret: !secret spotify_api
# o365:
#   client_secret: !secret o365_api
#   client_id: !secret o365_app
# toon:
#   client_id: !secret TOON_CONSUMER_KEY
#   client_secret: !secret TOON_CONSUMER_SECRET
# sonoff:
#   username: !secret gmail
#   password: !secret kruisweg
