- platform: group
  name: Plafond Spots
  entities:
    - light.ikea_spot_1
    - light.ikea_spot_2
    - light.ikea_spot_3

- platform: switch
  name: Schuur Deur
  entity_id: switch.sonoff_11

- platform: switch
  name: Schuur Top Licht
  entity_id: switch.sonoff_12

- platform: switch
  name: Schuur Ingang
  entity_id: switch.schuur_ingang

- platform: switch
  name: Tuin Overhang
  entity_id: switch.overhangbuiten

# - platform: switch
#   name: Badkamer schakelaar
#   entity_id: switch.shelly_01

# - platform: switch
#   name: Spiegel
#   entity_id: switch.sonoff_01

- platform: group
  name: Lichten Woonkamer
  entities:
    # - light.hue_filament
    - light.plant_lamp
    - light.achter_muur
    - light.zithoek_muur
    - light.diner_muur
    - light.plant_muur
    - light.plant_lamp
    # - light.hue_color_lamp_ikeasta
    # - light.hue_artimide_kast
    # - light.plafond

- platform: group
  name: Lichten Slaapkamer
  entities:
    - light.masterslaapkamer
    # - light.slaapkamerhuel
    # - light.kartel

- platform: group
  name: Noah Slaapkamer
  entities:
    - light.noahskamer
    - light.hue_color_lamp_ikeasta
    # - light.hue_color_lamp_kartbord

- platform: group
  name: Lichten Keuken
  entities:
    - light.keuken_muur
    - light.afzuigkap_light
    - light.keukenkastjehue
    - light.aanrechtblad
    # - light.gateway_light_7811dce188d1

- platform: group
  name: Lichten Tuin
  entities:
    - light.hue_outdoor_wall_1
    - light.tuin_overhang

- platform: group
  name: Lichten Kantoor
  entities:
    # - light.plafond_spots
    - light.hue_color_lamp_artimide
    - light.hue_color_lamp_kartbord

# - platform: group
#   name: Lichten Badkamer
#   entities:
# - light.spiegel
# - light.badkamer_schakelaar
# - light.ikea_badkamer

- platform: group
  name: Lichten Schuur
  entities:
    - light.schuur_deur
    - light.schuur_ingang
    - light.schuur_top_licht
# - platform: mqtt
# schema: json
# name: "Wemos LED 1"
# state_topic: "stat/wemos1/POWER"
# command_topic: "cmnd/wemos1/POWER"
# effect: true
# effect_list:
# - bpm
# - candy cane
# - confetti
# - cyclon rainbow
# - dots
# - fire
# - glitter
# - juggle
# - lightning
# - noise
# - police all
# - police one
# - rainbow
# - rainbow with glitter
# - ripple
# - sinelon
# - solid
# - twinkle
# brightness: true
# # flash: true
# rgb: true
# optimistic: false
# qos: 0

# - platform: mqtt
# schema: json
# name: "Wemos LED 2"
# state_topic: "stat/wemos2/POWER"
# command_topic: "cmnd/wemos2/POWER"
# effect: true
# effect_list:
# - bpm
# - candy cane
# - confetti
# - cyclon rainbow
# - dots
# - fire
# - glitter
# - juggle
# - lightning
# - noise
# - police all
# - police one
# - rainbow
# - rainbow with glitter
# - ripple
# - sinelon
# - solid
# - twinkle
# brightness: true
# # flash: true
# rgb: true
# optimistic: false
# qos: 0
