'use client'

import React, { createContext, useContext, useState } from 'react'

type Language = 'en' | 'nl'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  en: {
    // Navigation
    'nav.services': 'Services',
    'nav.shop': 'Shop',
    'nav.support': 'Support',
    'nav.about': 'About',
    'nav.itcheck': 'IT Check',
    'nav.networkscan': 'Network Scan',
    'nav.contact': 'Contact',
    'nav.support_tool': 'Remote Support',
    'nav.start_it_check': 'Start IT Check',
    
    // Hero Section - Professional tone
    'hero.title': 'Reliable IT Solutions for Amsterdam Businesses',
    'hero.subtitle': 'Professional IT support that helps your business grow efficiently',
    'hero.description': 'We provide comprehensive IT services to 200+ Amsterdam businesses, helping them reduce costs, improve security, and focus on what they do best. Local expertise, proven results.',
    'hero.cta.primary': 'Get Your IT Assessment',
    'hero.cta.secondary': 'Call Us Now',
    'hero.cta.time': '2 minutes',
    'hero.benefit.uptime': 'Proven Uptime',
    'hero.benefit.response': 'Quick Response',
    'hero.benefit.savings': 'Client Savings',
    'hero.badge.text': 'Serving 200+ Amsterdam businesses since 2015',
    'hero.bottom.guarantee': 'Free consultation • No obligations • Local Amsterdam team',
    
    // Stats Section
    'stats.title': '200+ Amsterdam Businesses Trust Our IT Solutions',
    'stats.description': 'From financial firms in Zuidas to creative agencies in Jordaan, we help businesses across Amsterdam optimize their technology infrastructure and reduce IT costs.',
    'stats.saved': 'Saved This Year',
    'stats.prevented': 'Issues Prevented',
    'stats.response': 'Avg Response Time',
    'stats.ransomware': 'Ransomware Paid',
    'stats.protected': '100% protected',
    'stats.measured': 'Measured over 12 months',
    'stats.phone_response': 'Average phone response',
    'stats.total_savings': 'Total client savings 2024',
    'stats.since_2015': 'Since 2015',
    'stats.average_2024': 'Average in 2024',
    
    // Services Section
    'services.title': 'Complete IT Solutions That Support Your Business Growth',
    'services.description': 'Our comprehensive services cover all your IT needs with transparent pricing and proven results. One reliable partner for all your technology requirements.',
    'services.view_all': 'View All Services',
    'services.managed_it.title': 'Managed IT Services',
    'services.managed_it.description': 'Complete IT support that costs less than hiring one full-time employee',
    'services.managed_it.highlight': '60% cost reduction',
    'services.managed_it.outcome': 'Focus on business growth',
    'services.cybersecurity.title': 'Cybersecurity',
    'services.cybersecurity.description': 'Professional security monitoring and threat protection for your business',
    'services.cybersecurity.highlight': '24/7 monitoring',
    'services.cybersecurity.outcome': 'Data stays secure',
    'services.cloud.title': 'Cloud Services',
    'services.cloud.description': 'Modern cloud infrastructure that supports remote work and business flexibility',
    'services.cloud.highlight': '45% infrastructure savings',
    'services.cloud.outcome': 'Work from anywhere',
    'services.consulting.title': 'IT Consulting',
    'services.consulting.description': 'Strategic technology guidance to support business objectives and growth',
    'services.consulting.highlight': 'Business-aligned IT',
    'services.consulting.outcome': 'Technology that works',
    'services.gdpr.title': 'GDPR Compliance',
    'services.gdpr.description': 'Complete privacy compliance support for Amsterdam businesses',
    'services.gdpr.highlight': 'Full compliance',
    'services.gdpr.outcome': 'Peace of mind',
    'services.network.title': 'Network Infrastructure',
    'services.network.description': 'Reliable networking solutions that keep your business connected',
    'services.network.highlight': '99.97% uptime',
    'services.network.outcome': 'Consistent connectivity',
    'services.backup.title': 'Data Backup & Recovery',
    'services.backup.description': 'Comprehensive backup solutions with quick data recovery when needed',
    'services.backup.highlight': 'Daily backups',
    'services.backup.outcome': 'Data protection',
    'services.support.title': '24/7 Support',
    'services.support.description': 'Local Amsterdam team available when you need technical assistance',
    'services.support.highlight': '4-minute response',
    'services.support.outcome': 'Help when you need it',
    'services.learn_more': 'Learn More',
    
    // Team Section
    'team.title': 'Your Local IT Team',
    'team.description': 'Amsterdam-based professionals with deep technical knowledge and genuine commitment to your business success.',
    'team.florian.name': 'Florian',
    'team.florian.role': 'Founder & CEO',
    'team.florian.expertise': 'Strategic IT Leadership',
    'team.namhoon.name': 'Nam-Hoon',
    'team.namhoon.role': 'Technical Director',
    'team.namhoon.expertise': 'Infrastructure & Security',
    'team.samir.name': 'Samir',
    'team.samir.role': 'Operations Manager',
    'team.samir.expertise': 'Service Delivery Excellence',
    'team.marcello.name': 'Marcello',
    'team.marcello.role': 'Solutions Architect',
    'team.marcello.expertise': 'Cloud & Innovation',
    
    // Testimonials
    'testimonials.title': 'What Our Clients Say',
    'testimonials.description': 'Real results from Amsterdam businesses who have improved their operations with our IT solutions.',
    'testimonials.more': 'Read more success stories',
    'testimonials.quote1': 'We needed reliable IT support as we grew from 15 to 50 employees. Workflo provided excellent service throughout our expansion, handling all technical challenges professionally. Their proactive approach helped us avoid downtime during critical client presentations.',
    'testimonials.author1': 'Marcus van den Berg',
    'testimonials.role1': 'CEO, Amsterdam Financial Partners',
    'testimonials.result1': 'Smooth business growth',
    'testimonials.stats1': '0 downtime during expansion • Professional support',
    'testimonials.quote2': 'Moving to Workflo reduced our IT costs by nearly 40% while significantly improving our system reliability. They provide clear communication and solve issues quickly. Our team can focus on development instead of technical problems.',
    'testimonials.author2': 'Sophie de Vries',
    'testimonials.role2': 'CTO, TechStart Amsterdam',
    'testimonials.result2': '40% cost reduction + improved reliability',
    'testimonials.stats2': 'Faster issue resolution • Better system stability',
    'testimonials.quote3': 'Workflo helped us scale from 15 to 75 employees without the usual IT complications. Their managed services approach means we have enterprise-level support at a fraction of the cost of an internal IT department.',
    'testimonials.author3': 'Maria van den Berg',
    'testimonials.role3': 'Founder, Creative Agency Oost',
    'testimonials.result3': 'Enterprise IT at SME cost',
    'testimonials.stats3': '5x team growth • Managed IT services • Cost-effective',
    
    // CTA Sections
    'cta.ready_title': 'Ready to Optimize Your IT Infrastructure?',
    'cta.ready_description': 'Join 200+ Amsterdam businesses that have improved their operations and reduced IT costs with our professional services.',
    'cta.assessment_title': 'Free IT Assessment',
    'cta.assessment_description': 'Get a comprehensive review of your current IT infrastructure and discover optimization opportunities:',
    'cta.assessment.security': 'Security assessment and recommendations',
    'cta.assessment.cost': 'Cost optimization analysis',
    'cta.assessment.backup': 'Backup and recovery evaluation',
    'cta.assessment.network': 'Network performance review',
    'cta.start_assessment': 'Start Free Assessment',
    'cta.call_today': 'Call Us Today',
    'cta.no_obligations': 'No obligations • Professional consultation • Local Amsterdam team',
    
    // About Page
    'about.hero.title': 'The Amsterdam IT Team That Actually Cares About Your Business Success',
    'about.hero.description': 'We started Workflo because we were tired of seeing Amsterdam businesses held back by their technology. Too many great companies were choosing between growth and IT costs, or worse, losing customers because their systems couldn&apos;t handle success.',
    'about.founded': 'Founded in Amsterdam',
    'about.clients': 'Happy Clients',
    'about.retention': 'Client Retention',
    'about.availability': 'Always Available',
    'about.story.title': 'Our Story',
    'about.story.quote': 'We don&apos;t believe in one-size-fits-all IT solutions.',
    'about.story.description1': 'Every Amsterdam business is unique. That&apos;s why we take time to understand your specific challenges, industry requirements, and growth ambitions before crafting your IT strategy.',
    'about.story.description2': 'Founded by entrepreneurs, for entrepreneurs. We understand the Amsterdam business landscape because we&apos;re part of it. We know that directness and reliability matter more than flashy presentations. That&apos;s why we focus on delivering measurable results, not just services.',
    'about.story.description3': 'Our team combines 15+ years of technical expertise with genuine business acumen. We don&apos;t just fix your IT – we align your technology with your business goals. When you succeed, we succeed. It&apos;s that simple.',
    'about.areas.zuidas': 'Zuidas',
    'about.areas.zuidas_description': 'Financial & Legal Firms',
    'about.areas.jordaan': 'Jordaan',
    'about.areas.jordaan_description': 'Creative Agencies',
    'about.areas.noord': 'Noord',
    'about.areas.noord_description': 'Tech Startups',
    'about.story.description4': 'From the historic Centrum to the innovative business districts, Workflo supports Amsterdam businesses across all sectors. We speak your language (literally and figuratively), understand your market, and know exactly what it takes to succeed here.',
    'about.team.title': 'Meet Our Team',
    'about.team.florian.description': 'With over 15 years in IT management, Florian leads our vision of making enterprise-grade IT accessible to Amsterdam SMEs.',
    'about.team.namhoon.description': 'Our infrastructure wizard ensures your systems are secure, scalable, and always available when you need them.',
    'about.team.samir.description': 'Mas ensures every client receives exceptional service and that our team delivers on every promise we make.',
    'about.team.marcello.description': 'Marcello designs innovative solutions that transform business challenges into competitive advantages.',
    'about.values.title': 'Our Values',
    'about.values.results.title': 'Results-Driven',
    'about.values.results.description': 'We measure our success by your business outcomes, not billable hours.',
    'about.values.partnership.title': 'True Partnership',
    'about.values.partnership.description': 'Your IT team, not just another vendor. We&apos;re invested in your growth.',
    'about.values.innovation.title': 'Proactive Innovation',
    'about.values.innovation.description': 'Staying ahead of problems and opportunities so you can focus on business.',
    'about.cta.title': 'Ready to Experience IT That Just Works?',
    'about.cta.description': 'Join 200+ Amsterdam businesses who trust Workflo',
    'about.cta.button': 'Start Your Free IT Assessment',
    
    // Contact Page
    'contact.hero.title': 'Stop With IT Stress, Start Growing',
    'contact.hero.description': 'Direct answer to your IT questions? Call us or fill out the form. Average response time: 15 minutes.',
    'contact.form.title': 'Send a Message',
    'contact.form.description': 'Fill out the form and we&apos;ll contact you within 24 hours. For urgent matters, you can call us directly.',
    'contact.direct.title': 'Direct Contact',
    'contact.direct.call': 'Call us directly',
    'contact.direct.email': 'Email us',
    'contact.direct.urgent': 'Urgent IT problems?',
    'contact.direct.response_time': 'Average response time: 15 minutes',
    'contact.office.title': 'Office Address',
    'contact.office.name': 'Workflo Amsterdam',
    'contact.office.hours.title': 'Opening Hours',
    'contact.office.hours.weekdays': 'Mon-Fri: 9:00 - 17:00',
    'contact.office.hours.support': '24/7 support for contract clients',
    'contact.route': 'Plan route',
    'contact.quick_help.title': 'Need Quick Answer?',
    'contact.quick_help.description': 'Check our IT Health Check to immediately see if your current IT partner is performing well.',
    'contact.quick_help.button': 'Start IT Health Check',
    'contact.map.title': 'Come By For A Cup of Coffee',
    'contact.whatsapp.title': 'WhatsApp Business',
    'contact.whatsapp.description': 'Chat directly with our team',
    'contact.whatsapp.cta': 'Start WhatsApp →',
    'contact.schedule.title': 'Schedule a Meeting',
    'contact.schedule.description': 'In person or online',
    'contact.schedule.cta': 'Choose a time slot →',
    'contact.support.title': 'Support Portal',
    'contact.support.description': 'For existing clients',
    'contact.support.cta': 'Login support →',
    
    // Tevredenheidscheck Page
    'tevredenheidscheck.title': 'IT Service Provider Check',
    'tevredenheidscheck.subtitle': 'Discover in 2 minutes if your IT partner really takes care of you',
    'tevredenheidscheck.guarantee': 'Honest advice • No obligations • Direct results',
    
    // Services Page
    'diensten.hero.title': 'IT Problems? We Know Your Industry',
    'diensten.hero.description': 'From retail peaks to healthcare compliance. Specific solutions for your sector.',
    'diensten.years_experience': 'Years experience',
    'diensten.specializations': 'Specializations',
    'diensten.industry_knowledge': 'Industry knowledge',
    'diensten.retail.industry': 'Retail & E-commerce',
    'diensten.retail.main_problem': 'Cash register fails during Black Friday?',
    'diensten.retail.also_problems': 'Also experiencing:',
    'diensten.retail.sub1': 'Webshop crashes during busy periods',
    'diensten.retail.sub2': 'Inventory system not real-time',
    'diensten.retail.sub3': 'Payment provider outages',
    'diensten.retail.emotion': 'Never miss revenue due to IT problems again',
    'diensten.retail.solution': 'Scalable cloud solutions that grow with peak moments. From POS systems to webshop hosting.',
    'diensten.retail.case_client': 'Amsterdam Fashion Retailer',
    'diensten.retail.case_problem': 'Webshop crashed at every sale',
    'diensten.retail.case_result': '300% more capacity, 0 downtime during Black Friday',
    'diensten.retail.cta': 'Discuss Retail & E-commerce solution',
    'diensten.office.industry': 'Offices & Business services',
    'diensten.office.main_problem': 'Team can&apos;t log in on Monday morning?',
    'diensten.office.sub1': 'VPN doesn&apos;t work at home',
    'diensten.office.sub2': 'Files not accessible',
    'diensten.office.sub3': 'Video calls constantly stuttering',
    'diensten.office.emotion': 'Productive work, at the office and at home',
    'diensten.office.solution': 'Modern workplace solutions with Microsoft 365 and secure remote access for hybrid working.',
    'diensten.office.case_client': 'Law Firm Zuid-As',
    'diensten.office.case_problem': 'Files not safely accessible at home',
    'diensten.office.case_result': 'Secure cloud solution, 50% more efficient working',
    'diensten.office.cta': 'Discuss Offices & Business services solution',
    'diensten.healthcare.industry': 'Healthcare & Welfare',
    'diensten.healthcare.main_problem': 'Patient data unreachable during emergency?',
    'diensten.healthcare.sub1': 'EPD system slow',
    'diensten.healthcare.sub2': 'GDPR compliance concerns',
    'diensten.healthcare.sub3': 'Equipment not connected',
    'diensten.healthcare.emotion': 'Focus on care, not worries about IT',
    'diensten.healthcare.solution': 'GDPR-compliant IT with 24/7 availability. Especially for healthcare institutions.',
    'diensten.healthcare.case_client': 'GP Practice Amsterdam Noord',
    'diensten.healthcare.case_problem': 'EPD unreachable during weekend service',
    'diensten.healthcare.case_result': '99.9% uptime, NEN 7510 certified',
    'diensten.healthcare.cta': 'Discuss Healthcare & Welfare solution',
    'diensten.financial.industry': 'Financial services',
    'diensten.financial.main_problem': 'Sensitive data leaked? AFM fine?',
    'diensten.financial.sub1': 'Not DNB compliant',
    'diensten.financial.sub2': 'Transactions delayed',
    'diensten.financial.sub3': 'Audit trail missing',
    'diensten.financial.emotion': 'Comply with all rules without headaches',
    'diensten.financial.solution': 'Compliance-first IT infrastructure for financials. DNB/AFM proof.',
    'diensten.financial.case_client': 'Asset Manager Zuidas',
    'diensten.financial.case_problem': 'DNB audit threatened to fail',
    'diensten.financial.case_result': 'Fully compliant within 3 months',
    'diensten.financial.cta': 'Discuss Financial services solution',
    'diensten.education.industry': 'Education & Training',
    'diensten.education.main_problem': 'Online class fails during exam?',
    'diensten.education.sub1': 'Students cannot log in',
    'diensten.education.sub2': 'Course materials not available',
    'diensten.education.sub3': 'Digital testing fails',
    'diensten.education.emotion': 'Education always continues, even digitally',
    'diensten.education.solution': 'Reliable education platforms with guaranteed availability during peak moments.',
    'diensten.education.case_client': 'HBO Institution Amsterdam',
    'diensten.education.case_problem': 'Platform crashed during exams',
    'diensten.education.case_result': '5000 simultaneous users, no problems',
    'diensten.education.cta': 'Discuss Education & Training solution',
    'diensten.logistics.industry': 'Logistics & Transport',
    'diensten.logistics.main_problem': 'Track & trace offline? Angry customers?',
    'diensten.logistics.sub1': 'WMS system stuttering',
    'diensten.logistics.sub2': 'Driver apps not working',
    'diensten.logistics.sub3': 'Real-time tracking fails',
    'diensten.logistics.emotion': 'Deliveries always on time thanks to stable IT',
    'diensten.logistics.solution': 'Robust logistics IT systems with real-time tracking and 100% uptime guarantee.',
    'diensten.logistics.case_client': 'Last-mile delivery Amsterdam',
    'diensten.logistics.case_problem': 'Tracking app failed 3x per week',
    'diensten.logistics.case_result': 'Zero downtime in 6 months',
    'diensten.logistics.cta': 'Discuss Logistics & Transport solution',
    'diensten.case_example': 'Practical example',
    'diensten.case_result': 'Result:',
    'diensten.tech_specs': 'Technical specifications',
    'diensten.bottom.title': 'Your industry not listed?',
    'diensten.bottom.description': 'No problem! We have a solution for every sector.',
    'diensten.bottom.cta1': 'Do the Industry IT Scan',
    'diensten.bottom.cta2': 'Call for Sector Advice',
    
    // Footer
    'footer.tagline': "Amsterdam's Most Trusted IT Partner",
    'footer.write_review': 'Write a Review',
    'footer.services': 'Services',
    'footer.company': 'Company',
    'footer.industries': 'Industries',
    'footer.rights': 'All rights reserved',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms & Conditions',
    'common.email': 'Email',
    'common.phone': 'Phone',
    'common.address': 'Address',
  },
  nl: {
    // Navigation
    'nav.services': 'Diensten',
    'nav.shop': 'Winkel',
    'nav.support': 'Ondersteuning',
    'nav.about': 'Over Ons',
    'nav.itcheck': 'IT Check',
    'nav.networkscan': 'Netwerk Scan',
    'nav.contact': 'Contact',
    'nav.support_tool': 'Externe Ondersteuning',
    'nav.start_it_check': 'Start IT Check',
    
    // Hero Section - Dutch professional tone
    'hero.title': 'Betrouwbare IT-oplossingen voor Amsterdamse Bedrijven',
    'hero.subtitle': 'Professionele IT-ondersteuning die uw bedrijf helpt efficiënt te groeien',
    'hero.description': 'Wij leveren complete IT-diensten aan meer dan 200 Amsterdamse bedrijven en helpen hen kosten te verlagen, beveiliging te verbeteren en zich te concentreren op waar ze goed in zijn. Lokale expertise, bewezen resultaten.',
    'hero.cta.primary': 'Vraag Uw IT-scan Aan',
    'hero.cta.secondary': 'Bel Ons Nu',
    'hero.cta.time': '2 minuten',
    'hero.benefit.uptime': 'Bewezen Uptime',
    'hero.benefit.response': 'Snelle Reactie',
    'hero.benefit.savings': 'Klantbesparingen',
    'hero.badge.text': 'Meer dan 200 Amsterdamse bedrijven vertrouwen ons sinds 2015',
    'hero.bottom.guarantee': 'Gratis consultatie • Geen verplichtingen • Lokaal Amsterdams team',
    
    // Stats Section
    'stats.title': 'Meer dan 200 Amsterdamse Bedrijven Vertrouwen Onze IT-oplossingen',
    'stats.description': 'Van financiële bedrijven op de Zuidas tot creatieve bureaus in de Jordaan, wij helpen bedrijven door heel Amsterdam hun technologie-infrastructuur te optimaliseren en IT-kosten te verlagen.',
    'stats.saved': 'Bespaard Dit Jaar',
    'stats.prevented': 'Problemen Voorkomen',
    'stats.response': 'Gem. Reactietijd',
    'stats.ransomware': 'Ransomware Betaald',
    'stats.protected': '100% beschermd',
    'stats.measured': 'Gemeten over 12 maanden',
    'stats.phone_response': 'Gemiddelde telefoonreactie',
    'stats.total_savings': 'Totale klantbesparing 2024',
    'stats.since_2015': 'Sinds 2015',
    'stats.average_2024': 'Gemiddelde in 2024',
    
    // Services Section
    'services.title': 'Complete IT-oplossingen Die Uw Bedrijfsgroei Ondersteunen',
    'services.description': 'Onze uitgebreide diensten dekken al uw IT-behoeften met transparante prijzen en bewezen resultaten. Één betrouwbare partner voor al uw technologische vereisten.',
    'services.view_all': 'Bekijk Alle Diensten',
    'services.managed_it.title': 'Managed IT Diensten',
    'services.managed_it.description': 'Complete IT-ondersteuning die minder kost dan het inhuren van één fulltime medewerker',
    'services.managed_it.highlight': '60% kostenverlaging',
    'services.managed_it.outcome': 'Focus op bedrijfsgroei',
    'services.cybersecurity.title': 'Cybersecurity',
    'services.cybersecurity.description': 'Professionele beveiligingsmonitoring en bedreigingsbescherming voor uw bedrijf',
    'services.cybersecurity.highlight': '24/7 monitoring',
    'services.cybersecurity.outcome': 'Data blijft veilig',
    'services.cloud.title': 'Cloud Diensten',
    'services.cloud.description': 'Moderne cloud-infrastructuur die thuiswerken en bedrijfsflexibiliteit ondersteunt',
    'services.cloud.highlight': '45% infrastructuurbesparing',
    'services.cloud.outcome': 'Werk overal vandaan',
    'services.consulting.title': 'IT Consultancy',
    'services.consulting.description': 'Strategische technologiebegeleiding ter ondersteuning van bedrijfsdoelen en groei',
    'services.consulting.highlight': 'Bedrijfsgericht IT',
    'services.consulting.outcome': 'Technologie die werkt',
    'services.gdpr.title': 'GDPR Compliance',
    'services.gdpr.description': 'Complete privacycompliance ondersteuning voor Amsterdamse bedrijven',
    'services.gdpr.highlight': 'Volledige compliance',
    'services.gdpr.outcome': 'Gemoedsrust',
    'services.network.title': 'Netwerkinfrastructuur',
    'services.network.description': 'Betrouwbare netwerkoplossingen die uw bedrijf verbonden houden',
    'services.network.highlight': '99,97% uptime',
    'services.network.outcome': 'Consistente connectiviteit',
    'services.backup.title': 'Data Backup & Recovery',
    'services.backup.description': 'Uitgebreide backup-oplossingen met snelle dataherstel wanneer nodig',
    'services.backup.highlight': 'Dagelijkse backups',
    'services.backup.outcome': 'Databescherming',
    'services.support.title': '24/7 Support',
    'services.support.description': 'Lokaal Amsterdams team beschikbaar wanneer u technische assistentie nodig hebt',
    'services.support.highlight': '4-minuten reactie',
    'services.support.outcome': 'Hulp wanneer u het nodig hebt',
    'services.learn_more': 'Meer Informatie',
    
    // Team Section
    'team.title': 'Uw Lokale IT-team',
    'team.description': 'Amsterdamse professionals met diepgaande technische kennis en oprechte betrokkenheid bij uw bedrijfssucces.',
    'team.florian.name': 'Florian',
    'team.florian.role': 'Oprichter & CEO',
    'team.florian.expertise': 'Strategisch IT Leiderschap',
    'team.namhoon.name': 'Nam-Hoon',
    'team.namhoon.role': 'Technisch Directeur',
    'team.namhoon.expertise': 'Infrastructuur & Beveiliging',
    'team.samir.name': 'Samir',
    'team.samir.role': 'Operations Manager',
    'team.samir.expertise': 'Service Delivery Excellence',
    'team.marcello.name': 'Marcello',
    'team.marcello.role': 'Solutions Architect',
    'team.marcello.expertise': 'Cloud & Innovatie',
    
    // Testimonials
    'testimonials.title': 'Wat Onze Klanten Zeggen',
    'testimonials.description': 'Echte resultaten van Amsterdamse bedrijven die hun activiteiten hebben verbeterd met onze IT-oplossingen.',
    'testimonials.more': 'Lees meer succesverhalen',
    'testimonials.quote1': 'Wij hadden betrouwbare IT-ondersteuning nodig toen we groeiden van 15 naar 50 medewerkers. Workflo leverde uitstekende service tijdens onze expansie en handelde alle technische uitdagingen professioneel af. Hun proactieve aanpak hielp ons downtime te voorkomen tijdens kritieke klantpresentaties.',
    'testimonials.author1': 'Marcus van den Berg',
    'testimonials.role1': 'CEO, Amsterdam Financial Partners',
    'testimonials.result1': 'Soepele bedrijfsgroei',
    'testimonials.stats1': '0 downtime tijdens expansie • Professionele ondersteuning',
    'testimonials.quote2': 'Overstappen naar Workflo verlaagde onze IT-kosten met bijna 40% terwijl de systeembetrouwbaarheid aanzienlijk verbeterde. Ze bieden duidelijke communicatie en lossen problemen snel op. Ons team kan zich richten op ontwikkeling in plaats van technische problemen.',
    'testimonials.author2': 'Sophie de Vries',
    'testimonials.role2': 'CTO, TechStart Amsterdam',
    'testimonials.result2': '40% kostenverlaging + verbeterde betrouwbaarheid',
    'testimonials.stats2': 'Snellere probleemoplossing • Betere systeemstabiliteit',
    'testimonials.quote3': 'Workflo hielp ons schalen van 15 naar 75 medewerkers zonder de gebruikelijke IT-complicaties. Hun managed services aanpak betekent dat we enterprise-level ondersteuning hebben voor een fractie van de kosten van een interne IT-afdeling.',
    'testimonials.author3': 'Maria van den Berg',
    'testimonials.role3': 'Oprichter, Creative Agency Oost',
    'testimonials.result3': 'Enterprise IT tegen MKB kosten',
    'testimonials.stats3': '5x teamgroei • Managed IT services • Kosteneffectief',
    
    // CTA Sections
    'cta.ready_title': 'Klaar om Uw IT-infrastructuur te Optimaliseren?',
    'cta.ready_description': 'Sluit u aan bij 200+ Amsterdamse bedrijven die hun activiteiten hebben verbeterd en IT-kosten hebben verlaagd met onze professionele diensten.',
    'cta.assessment_title': 'Gratis IT Assessment',
    'cta.assessment_description': 'Krijg een uitgebreide beoordeling van uw huidige IT-infrastructuur en ontdek optimalisatiemogelijkheden:',
    'cta.assessment.security': 'Beveiligingsbeoordeling en aanbevelingen',
    'cta.assessment.cost': 'Kostenoptimalisatie analyse',
    'cta.assessment.backup': 'Backup en recovery evaluatie',
    'cta.assessment.network': 'Netwerkprestatie review',
    'cta.start_assessment': 'Start Gratis Assessment',
    'cta.call_today': 'Bel Ons Vandaag',
    'cta.no_obligations': 'Geen verplichtingen • Professionele consultatie • Lokaal Amsterdams team',
    
    // About Page
    'about.hero.title': 'Het Amsterdamse IT-team Dat Echt Geeft om Uw Bedrijfssucces',
    'about.hero.description': 'Wij startten Workflo omdat we het zat waren om Amsterdamse bedrijven te zien tegengehouden door hun technologie. Te veel geweldige bedrijven moesten kiezen tussen groei en IT-kosten, of erger nog, klanten verliezen omdat hun systemen het succes niet aankonden.',
    'about.founded': 'Opgericht in Amsterdam',
    'about.clients': 'Tevreden Klanten',
    'about.retention': 'Klantretentie',
    'about.availability': 'Altijd Bereikbaar',
    'about.story.title': 'Ons Verhaal',
    'about.story.quote': 'Wij geloven niet in one-size-fits-all IT-oplossingen.',
    'about.story.description1': 'Elk Amsterdams bedrijf is uniek. Daarom nemen wij de tijd om uw specifieke uitdagingen, branchevereisten en groeiambities te begrijpen voordat we uw IT-strategie opstellen.',
    'about.story.description2': 'Opgericht door ondernemers, voor ondernemers. Wij begrijpen het Amsterdamse bedrijfslandschap omdat wij er deel van uitmaken. Wij weten dat directheid en betrouwbaarheid belangrijker zijn dan flashy presentaties. Daarom richten we ons op het leveren van meetbare resultaten, niet alleen diensten.',
    'about.story.description3': 'Ons team combineert 15+ jaar technische expertise met oprechte bedrijfskennis. Wij repareren niet alleen uw IT – wij stemmen uw technologie af op uw bedrijfsdoelen. Wanneer u succesvol bent, zijn wij dat ook. Zo simpel is het.',
    'about.areas.zuidas': 'Zuidas',
    'about.areas.zuidas_description': 'Financiële & Juridische Bedrijven',
    'about.areas.jordaan': 'Jordaan',
    'about.areas.jordaan_description': 'Creatieve Bureaus',
    'about.areas.noord': 'Noord',
    'about.areas.noord_description': 'Tech Startups',
    'about.story.description4': 'Van het historische Centrum tot de innovatieve bedrijfsdistricten, Workflo ondersteunt Amsterdamse bedrijven in alle sectoren. Wij spreken uw taal (letterlijk en figuurlijk), begrijpen uw markt en weten precies wat er nodig is om hier te slagen.',
    'about.team.title': 'Maak Kennis Met Ons Team',
    'about.team.florian.description': 'Met meer dan 15 jaar ervaring in IT-management leidt Florian onze visie om enterprise-level IT toegankelijk te maken voor Amsterdamse MKB-bedrijven.',
    'about.team.namhoon.description': 'Onze infrastructuur-wizard zorgt ervoor dat uw systemen veilig, schaalbaar en altijd beschikbaar zijn wanneer u ze nodig hebt.',
    'about.team.samir.description': 'Mas zorgt ervoor dat elke klant uitzonderlijke service ontvangt en dat ons team elke belofte nakomt die we maken.',
    'about.team.marcello.description': 'Marcello ontwerpt innovatieve oplossingen die bedrijfsuitdagingen omzetten in concurrentievoordelen.',
    'about.values.title': 'Onze Waarden',
    'about.values.results.title': 'Resultaatgericht',
    'about.values.results.description': 'Wij meten ons succes af aan uw bedrijfsresultaten, niet aan declarabele uren.',
    'about.values.partnership.title': 'Echte Partnerschap',
    'about.values.partnership.description': 'Uw IT-team, niet zomaar een leverancier. Wij zijn geïnvesteerd in uw groei.',
    'about.values.innovation.title': 'Proactieve Innovatie',
    'about.values.innovation.description': 'Voor blijven op problemen en kansen zodat u zich kunt concentreren op zakendoen.',
    'about.cta.title': 'Klaar om IT te Ervaren Die Gewoon Werkt?',
    'about.cta.description': 'Sluit u aan bij 200+ Amsterdamse bedrijven die Workflo vertrouwen',
    'about.cta.button': 'Start Uw Gratis IT Assessment',
    
    // Contact Page
    'contact.hero.title': 'Stop Met IT-Stress, Begin Met Groeien',
    'contact.hero.description': 'Direct antwoord op uw IT-vragen? Bel ons of vul het formulier in. Gemiddelde reactietijd: 15 minuten.',
    'contact.form.title': 'Verstuur een Bericht',
    'contact.form.description': 'Vul het formulier in en we nemen binnen 24 uur contact met u op. Voor urgente zaken kunt u ons direct bellen.',
    'contact.direct.title': 'Direct Contact',
    'contact.direct.call': 'Bel ons direct',
    'contact.direct.email': 'Mail ons',
    'contact.direct.urgent': 'Urgente IT-problemen?',
    'contact.direct.response_time': 'Gemiddelde reactietijd: 15 minuten',
    'contact.office.title': 'Kantooradres',
    'contact.office.name': 'Workflo Amsterdam',
    'contact.office.hours.title': 'Openingstijden',
    'contact.office.hours.weekdays': 'Ma-Vr: 9:00 - 17:00',
    'contact.office.hours.support': '24/7 support voor contractklanten',
    'contact.route': 'Route plannen',
    'contact.quick_help.title': 'Snel Antwoord Nodig?',
    'contact.quick_help.description': 'Check onze IT Health Check om direct te zien of uw huidige IT-partner goed presteert.',
    'contact.quick_help.button': 'Start IT Health Check',
    'contact.map.title': 'Kom Langs Voor Een Kop Koffie',
    'contact.whatsapp.title': 'WhatsApp Business',
    'contact.whatsapp.description': 'Chat direct met ons team',
    'contact.whatsapp.cta': 'Start WhatsApp →',
    'contact.schedule.title': 'Plan een Meeting',
    'contact.schedule.description': 'Persoonlijk of online',
    'contact.schedule.cta': 'Kies een tijdslot →',
    'contact.support.title': 'Support Portal',
    'contact.support.description': 'Voor bestaande klanten',
    'contact.support.cta': 'Login support →',
    
    // Tevredenheidscheck Page
    'tevredenheidscheck.title': 'IT-Dienstverlener Check',
    'tevredenheidscheck.subtitle': 'Ontdek in 2 minuten of uw IT-partner écht voor u zorgt',
    'tevredenheidscheck.guarantee': 'Eerlijk advies • Geen verplichtingen • Direct resultaat',
    
    // Services Page
    'diensten.hero.title': 'IT-problemen? Wij kennen uw branche',
    'diensten.hero.description': 'Van retail-pieken tot zorg-compliance. Specifieke oplossingen voor uw sector.',
    'diensten.years_experience': 'Jaar ervaring',
    'diensten.specializations': 'Specialisaties',
    'diensten.industry_knowledge': 'Branche-kennis',
    'diensten.retail.industry': 'Retail & E-commerce',
    'diensten.retail.main_problem': 'Kassa valt uit tijdens Black Friday?',
    'diensten.retail.also_problems': 'Ook last van:',
    'diensten.retail.sub1': 'Webshop ligt plat bij drukte',
    'diensten.retail.sub2': 'Voorraadsysteem niet real-time',
    'diensten.retail.sub3': 'Payment provider storingen',
    'diensten.retail.emotion': 'Nooit meer omzet missen door IT-problemen',
    'diensten.retail.solution': 'Schaalbare cloud-oplossingen die meegroeien met piekmomenten. Van kassasystemen tot webshop hosting.',
    'diensten.retail.case_client': 'Amsterdamse Fashion Retailer',
    'diensten.retail.case_problem': 'Webshop crashte bij elke sale',
    'diensten.retail.case_result': '300% meer capaciteit, 0 downtime tijdens Black Friday',
    'diensten.retail.cta': 'Bespreek Retail & E-commerce oplossing',
    'diensten.office.industry': 'Kantoren & Zakelijke diensten',
    'diensten.office.main_problem': 'Team kan niet inloggen op maandagochtend?',
    'diensten.office.sub1': 'VPN werkt niet thuis',
    'diensten.office.sub2': 'Bestanden niet toegankelijk',
    'diensten.office.sub3': 'Video-calls haperen constant',
    'diensten.office.emotion': 'Productief werken, op kantoor én thuis',
    'diensten.office.solution': 'Modern workplace oplossingen met Microsoft 365 en veilige remote access voor hybride werken.',
    'diensten.office.case_client': 'Advocatenkantoor Zuid-As',
    'diensten.office.case_problem': 'Dossiers niet veilig toegankelijk thuis',
    'diensten.office.case_result': 'Veilige cloud-oplossing, 50% efficiënter werken',
    'diensten.office.cta': 'Bespreek Kantoren & Zakelijke diensten oplossing',
    'diensten.healthcare.industry': 'Zorg & Welzijn',
    'diensten.healthcare.main_problem': 'Patiëntgegevens onbereikbaar tijdens nood?',
    'diensten.healthcare.sub1': 'EPD systeem traag',
    'diensten.healthcare.sub2': 'GDPR compliance zorgen',
    'diensten.healthcare.sub3': 'Apparatuur niet verbonden',
    'diensten.healthcare.emotion': 'Focus op zorg, niet op zorgen over IT',
    'diensten.healthcare.solution': 'GDPR-compliant IT met 24/7 beschikbaarheid. Speciaal voor zorginstellingen.',
    'diensten.healthcare.case_client': 'Huisartsenpraktijk Amsterdam Noord',
    'diensten.healthcare.case_problem': 'EPD onbereikbaar tijdens weekend-dienst',
    'diensten.healthcare.case_result': '99,9% uptime, NEN 7510 gecertificeerd',
    'diensten.healthcare.cta': 'Bespreek Zorg & Welzijn oplossing',
    'diensten.financial.industry': 'Financiële dienstverlening',
    'diensten.financial.main_problem': 'Gevoelige data gelekt? AFM boete?',
    'diensten.financial.sub1': 'Niet DNB compliant',
    'diensten.financial.sub2': 'Transacties vertraagd',
    'diensten.financial.sub3': 'Audit trail ontbreekt',
    'diensten.financial.emotion': 'Voldoe aan alle regels zonder hoofdpijn',
    'diensten.financial.solution': 'Compliance-first IT infrastructuur voor financials. DNB/AFM proof.',
    'diensten.financial.case_client': 'Vermogensbeheerder Zuidas',
    'diensten.financial.case_problem': 'DNB audit dreigde te falen',
    'diensten.financial.case_result': 'Volledig compliant binnen 3 maanden',
    'diensten.financial.cta': 'Bespreek Financiële dienstverlening oplossing',
    'diensten.education.industry': 'Onderwijs & Training',
    'diensten.education.main_problem': 'Online les valt uit tijdens tentamen?',
    'diensten.education.sub1': 'Studenten kunnen niet inloggen',
    'diensten.education.sub2': 'Lesmateriaal niet beschikbaar',
    'diensten.education.sub3': 'Digitaal toetsen faalt',
    'diensten.education.emotion': 'Onderwijs gaat altijd door, ook digitaal',
    'diensten.education.solution': 'Betrouwbare onderwijsplatforms met gegarandeerde beschikbaarheid tijdens piekmomenten.',
    'diensten.education.case_client': 'HBO instelling Amsterdam',
    'diensten.education.case_problem': 'Platform crashte bij tentamens',
    'diensten.education.case_result': '5000 gelijktijdige gebruikers, geen problemen',
    'diensten.education.cta': 'Bespreek Onderwijs & Training oplossing',
    'diensten.logistics.industry': 'Logistiek & Transport',
    'diensten.logistics.main_problem': 'Track & trace offline? Klanten boos?',
    'diensten.logistics.sub1': 'WMS systeem hapert',
    'diensten.logistics.sub2': 'Chauffeurs apps werken niet',
    'diensten.logistics.sub3': 'Real-time tracking faalt',
    'diensten.logistics.emotion': 'Leveringen altijd op tijd dankzij stabiele IT',
    'diensten.logistics.solution': 'Robuuste logistieke IT-systemen met real-time tracking en 100% uptime garantie.',
    'diensten.logistics.case_client': 'Last-mile delivery Amsterdam',
    'diensten.logistics.case_problem': 'Tracking app viel 3x per week uit',
    'diensten.logistics.case_result': 'Zero downtime in 6 maanden',
    'diensten.logistics.cta': 'Bespreek Logistiek & Transport oplossing',
    'diensten.case_example': 'Praktijkvoorbeeld',
    'diensten.case_result': 'Resultaat:',
    'diensten.tech_specs': 'Technische specificaties',
    'diensten.bottom.title': 'Uw branche er niet bij?',
    'diensten.bottom.description': 'Geen probleem! Wij hebben voor elke sector een oplossing.',
    'diensten.bottom.cta1': 'Doe de Branche IT-Scan',
    'diensten.bottom.cta2': 'Bel voor Sectoradvies',
    
    // Footer
    'footer.tagline': "Amsterdam's Meest Vertrouwde IT Partner",
    'footer.write_review': 'Schrijf een Review',
    'footer.services': 'Diensten',
    'footer.company': 'Bedrijf',
    'footer.industries': 'Sectoren',
    'footer.rights': 'Alle rechten voorbehouden',
    'footer.privacy': 'Privacybeleid',
    'footer.terms': 'Algemene Voorwaarden',
    'common.email': 'E-mail',
    'common.phone': 'Telefoon',
    'common.address': 'Adres',
  }
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en')

  const t = (key: string) => {
    return translations[language][key as keyof typeof translations['en']] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}