blueprint:
  name: Toggle charger by battery
  description: Switch a smart-plug on or off depending on a battery's level
  domain: automation
  input:
    battery:
      name: Battery
      description: This battery's level will control the smart plug
      selector:
        entity:
          domain:
          - sensor
          device_class:
          - battery
          multiple: false
    person:
      name: Person
      description: But only when this person is in the specified state
      selector:
        entity:
          domain:
          - person
          multiple: false
    state:
      name: Person State
      description: The state the person must be in
      default: home
    target_switch:
      name: Smart Plug
      description: The smart plug to switch on or off
      selector:
        entity:
          domain:
          - switch
          multiple: false
    charge_min:
      name: Lowest Battery Charge
      description: The lowest charge the battery should be allowed to drop to
      selector:
        number:
          min: 0.0
          max: 95.0
          step: 5.0
          unit_of_measurement: '%'
          mode: slider
      default: 30
    charge_max:
      name: Highest Battery Charge
      description: The highest charge the battery should be allowed to reach
      selector:
        number:
          min: 5.0
          max: 100.0
          step: 5.0
          unit_of_measurement: '%'
          mode: slider
      default: 80
    use_bedtime:
      name: Charge fully before bed
      selector:
        boolean: {}
      default: true
    bedtime:
      name: Bedtime
      description: Allow full charge after this hour
      selector:
        time: {}
      default: '22:00'
    bedtime_latest:
      name: Latest Bedtime
      description: Stop allowing full charge after this hour
      selector:
        time: {}
      default: 03:00
    charge_full:
      name: Full Battery Charge
      description: The battery is considered full at this percentage
      selector:
        number:
          min: 75.0
          max: 100.0
          step: 5.0
          unit_of_measurement: '%'
          mode: slider
      default: 85
  source_url: https://community.home-assistant.io/t/toggle-switch-on-off-by-battery-phone-level/395023
variables:
  battery: !input battery
  charge_min: !input charge_min
  charge_max: !input charge_max
  charge_full: !input charge_full
  use_bedtime: !input use_bedtime
  bedtime: !input bedtime
  bedtime_latest: !input bedtime_latest
trigger:
- platform: state
  entity_id: !input battery
- platform: state
  entity_id: !input person
condition:
- condition: state
  entity_id: !input person
  state: !input state
action:
- variables:
    charge: '{{ (states(battery) | float) if is_number(states(battery)) else 1 }}'
    is_bedtime: '{{ use_bedtime == True and ( now() >= today_at(bedtime) or now()
      < today_at(bedtime_latest) ) }}'
    c_max: '{{ charge_full if is_bedtime else charge_max }}'
    c_min: '{{ charge_full if is_bedtime else charge_min }}'
- choose:
  - conditions: '{{ charge < c_min }}

      '
    sequence:
    - service: switch.turn_on
      target:
        entity_id: !input target_switch
  - conditions: '{{ charge >= c_max }}

      '
    sequence:
    - service: switch.turn_off
      target:
        entity_id: !input target_switch
