#!/bin/bash

echo "🔧 Starting Vercel build script..."
echo "================================"

# Show current directory
echo "📁 Current directory: $(pwd)"
echo ""

# Show git status
echo "📊 Git status:"
git status --short || echo "Git not available"
echo ""

# Show recent commits
echo "📝 Recent commits:"
git log --oneline -5 || echo "Git log not available"
echo ""

# Remove any cached AboutPageServer.tsx
echo "🗑️  Removing AboutPageServer.tsx if it exists..."
rm -rf app/about/AboutPageServer.tsx || true
rm -rf ./app/about/AboutPageServer.tsx || true
rm -rf /vercel/path0/app/about/AboutPageServer.tsx || true

# Create a dummy file to ensure it's overwritten
echo "📝 Creating safe AboutPageServer.tsx..."
mkdir -p app/about
echo "// This file was auto-generated by vercel-build.sh" > app/about/AboutPageServer.tsx
echo "export { default } from './page'" >> app/about/AboutPageServer.tsx
echo "export * from './page'" >> app/about/AboutPageServer.tsx

# Show what's in the about directory
echo ""
echo "📋 Contents of app/about/:"
ls -la app/about/ || echo "Directory not found"

# Show the contents of AboutPageServer.tsx if it exists
echo ""
echo "📄 Contents of AboutPageServer.tsx:"
cat app/about/AboutPageServer.tsx || echo "File not found"

# Check if the file still exists anywhere
echo ""
echo "🔍 Searching for AboutPageServer.tsx:"
find . -name "AboutPageServer.tsx" -type f 2>/dev/null | grep -v node_modules || echo "✅ No AboutPageServer.tsx found (good!)"

# Now run the actual build
echo ""
echo "🏗️  Running Next.js build..."
npm run build